import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.employers": "For Employers",
    "nav.candidates": "For Candidates",
    "nav.contact": "Contact Us",
    "nav.getStarted": "Get Started",
    "nav.about": "About Us",

    // Home Page
    "home.hero.title1": "Connecting Talent,",
    "home.hero.title2": "Building Futures",
    "home.hero.subtitle": "Bridge the gap between Latin American professionals and Canadian opportunities with HR-CALATIN Interexchange",
    "home.hero.employers": "For Employers",
    "home.hero.candidates": "For Candidates",

    "home.mission.title": "Our",
    "home.mission.titleHighlight": "Mission",
    "home.mission.description": "We connect the best talent from Latin America with Canadian companies. We facilitate labor integration by creating real growth opportunities for professionals and visionary employers.",

    "home.why.title": "Why Choose",
    "home.why.titleHighlight": "HR-CALATIN",
    "home.why.subtitle": "Connections that Work",
    "home.why.expertise.title": "Experts in Both Worlds",
    "home.why.expertise.description": "We master the Canadian market and know the Latin potential. We align company goals with candidate aspirations for a perfect fit.",
    "home.why.quality.title": "Guaranteed Quality",
    "home.why.quality.description": "Rigorous validation. Companies receive high-level profiles and candidates access serious and reliable offers. No time wasted.",
    "home.why.support.title": "Successful Integration",
    "home.why.support.description": "Total accompaniment. We facilitate the professional's arrival and adaptation, ensuring peace of mind for the employer and confidence for the new talent.",

    "home.portal.employers.title": "For Employers",
    "home.portal.employers.description": "Access a curated pool of qualified Latin American professionals ready to contribute to your Canadian business success.",
    "home.portal.employers.item1": "Personalized talent search and matching",
    "home.portal.employers.item2": "Comprehensive skills assessments",
    "home.portal.employers.item3": "Integration and onboarding support",
    "home.portal.employers.button": "Explore Employer Portal",

    "home.portal.candidates.title": "For Candidates",
    "home.portal.candidates.description": "Launch your Canadian career with expert guidance, resources, and access to top employers seeking your talents.",
    "home.portal.candidates.item1": "Professional resume building tools",
    "home.portal.candidates.item2": "Job search and application tracking",
    "home.portal.candidates.item3": "Cultural integration resources",
    "home.portal.candidates.button": "Explore Candidate Portal",

    "home.pathways.title": "Legal Pathways",
    "home.pathways.titleHighlight": " to Canada",
    "home.pathways.subtitle": "At HR-CALATIN we are the bridge between Latin America's professional excellence and Canadian companies' vision. We create the perfect match: talent ready to add immediate value and career opportunities that transform lives.",
    "home.pathways.holiday.title": "Young Talent (Working Holiday)",
    "home.pathways.holiday.description": "Flexible workforce for Chile and Costa Rica. A perfect solution to cover temporary needs or trial periods that can evolve into permanent positions.",
    "home.pathways.fta.title": "Free Trade Agreements (FTA)",
    "home.pathways.fta.description": "We leverage trade agreements with Colombia, Panama, Peru, and Chile to expedite the entry of experts without complications. Ideal for Engineering, Technology, Healthcare, and Education sectors.",
    "home.pathways.fta.engineering": "Highly Qualified Professionals",
    "home.pathways.fta.engineeringDesc": "Focus: Speed and Qualified Professionals (Colombia, Panama, etc.)",
    "home.pathways.fta.healthcare": "",
    "home.pathways.fta.healthcareDesc": "",
    "home.pathways.fta.education": "",
    "home.pathways.fta.educationDesc": "",
    "home.pathways.sawp.title": "Agricultural Sector (SAWP)",
    "home.pathways.sawp.description": "We cover your harvest seasons with experienced workers from Mexico and the Caribbean. We guarantee reliable and legal workforce for the Canadian field.",

    "home.stats.placements": "Successful Placements",
    "home.stats.companies": "Partner Companies",
    "home.stats.satisfaction": "Satisfaction Rate",
    "home.stats.experience": "Years Experience",

    // Candidates Page
    "candidates.hero.title1": "Your Canadian",
    "candidates.hero.title2": "Career Starts Here",
    "candidates.hero.subtitle": "Transform your professional dreams into reality with expert guidance and access to top Canadian employers",
    "candidates.hero.button": "Create Your Profile Today",

    "candidates.why.title": "Your Ally to Succeed in Canada",
    "candidates.why.subtitle": "We are not just a job board. We are your safe bridge to a successful international career.",
    "candidates.why.jobs.title": "Verified Opportunities",
    "candidates.why.jobs.description": "Access real vacancies at Canadian companies specifically seeking Latin talent. No fake offers, only growth.",
    "candidates.why.resume.title": "High-Impact CV",
    "candidates.why.resume.description": "Transform your resume to 'Canadian Standard'. Tools and experts so your profile passes all selection filters.",
    "candidates.why.culture.title": "Cultural Mastery",
    "candidates.why.culture.description": "Learn the keys to the Canadian work environment. We teach you what isn't in books so you integrate from day one.",
    "candidates.why.relocation.title": "Arrival Support",
    "candidates.why.relocation.description": "Your move, simplified. Clear guidance on migration procedures and housing so you arrive with peace of mind.",
    "candidates.why.skills.title": "Skills Leveling",
    "candidates.why.skills.description": "Close the technical gap. Courses and certifications to align your competencies with what the Canadian industry demands today.",
    "candidates.why.coaching.title": "Career Strategy",
    "candidates.why.coaching.description": "Don't apply blindly. Receive expert mentorship and interview simulations to turn opportunities into job offers.",
    "candidates.why.legal.title": "Career & Goals Mentorship",
    "candidates.why.legal.description": "We don't just accompany you in the process, we boost your future. We guide your professional trajectory so you reach your goals, with guaranteed success inside or outside of Canada.",

    "candidates.training.title": "Training &",
    "candidates.training.titleHighlight": "Integration Support",
    "candidates.training.subtitle": "We prepare professionals for success in Canada with comprehensive training and integration programs",
    "candidates.training.language.title": "Language Training",
    "candidates.training.language.description": "Intensive English and French courses designed to achieve effective communication in the Canadian professional environment",
    "candidates.training.resume.title": "Resume Creation",
    "candidates.training.resume.description": "Expert advice to adapt your professional profile and CV to the standards and formats required by Canadian recruiters",
    "candidates.training.arrival.title": "First Steps in Canada",
    "candidates.training.arrival.description": "We support you with initial procedures: phone line, bank account opening, and other essentials for your new life",
    "candidates.training.button": "Learn More",

    "candidates.path.title": "Your Path to Success",
    "candidates.path.subtitle": "Four simple steps to launch your Canadian career",
    "candidates.path.step1.title": "Register",
    "candidates.path.step1.description": "Create your free account and complete your professional profile",
    "candidates.path.step2.title": "Build Resume",
    "candidates.path.step2.description": "Use our tools to create a compelling, Canadian-standard CV",
    "candidates.path.step3.title": "Apply",
    "candidates.path.step3.description": "Browse opportunities and apply to positions matching your skills",
    "candidates.path.step4.title": "Launch Career",
    "candidates.path.step4.description": "Get hired and receive ongoing support during your transition",

    "candidates.tools.title": "Powerful Tools for Your Success",
    "candidates.tools.subtitle": "Everything you need to stand out and succeed",
    "candidates.tools.resume.title": "Smart Resume Builder",
    "candidates.tools.resume.description": "AI-powered suggestions, industry-specific templates, and real-time feedback to create the perfect CV",
    "candidates.tools.search.title": "Job Search Dashboard",
    "candidates.tools.search.description": "Advanced filtering, personalized recommendations, and application tracking in one place",
    "candidates.tools.learning.title": "Learning Resources",
    "candidates.tools.learning.description": "Comprehensive guides on Canadian workplace culture, interview tips, and career development",
    "candidates.tools.acceleration.title": "Career Acceleration Program",
    "candidates.tools.acceleration.description": "Exclusive access to mentorship, networking events, and professional development workshops",

    "candidates.apply.title": "Apply Now!",
    "candidates.apply.subtitle": "Take the first step towards your Canadian career. Fill out our application form and our team will contact you.",

    "candidates.cta.title": "Contact Us",
    "candidates.cta.subtitle": "Have questions about our programs or services? We're here to help you every step of the way.",
    "candidates.cta.button": "Get in Touch",

    // Application Form
    "candidates.form.personal.title": "Personal Information",
    "candidates.form.personal.name": "Full Name *",
    "candidates.form.personal.namePlaceholder": "John Doe",
    "candidates.form.personal.email": "Email Address *",
    "candidates.form.personal.emailPlaceholder": "john@example.com",
    "candidates.form.personal.phone": "Phone Number",
    "candidates.form.personal.phonePlaceholder": "+1 123 456 7890",
    "candidates.form.personal.country": "Country of Residence *",
    "candidates.form.personal.countryPlaceholder": "Select your country",
    "candidates.form.personal.city": "City",
    "candidates.form.personal.cityPlaceholder": "Toronto",

    "candidates.form.professional.title": "Professional Information",
    "candidates.form.professional.profession": "Profession / Work Area *",
    "candidates.form.professional.professionPlaceholder": "Software Engineer",
    "candidates.form.professional.experience": "Years of Experience",
    "candidates.form.professional.experiencePlaceholder": "5",
    "candidates.form.professional.education": "Education Level",
    "candidates.form.professional.educationPlaceholder": "Select your level",
    "candidates.form.professional.sector": "Sector of Interest",
    "candidates.form.professional.sectorPlaceholder": "Select a sector",
    "candidates.form.professional.linkedin": "LinkedIn URL",
    "candidates.form.professional.linkedinPlaceholder": "https://linkedin.com/in/your-profile",

    "candidates.form.languages.title": "Languages",
    "candidates.form.languages.english": "English Level",
    "candidates.form.languages.french": "French Level",
    "candidates.form.languages.placeholder": "Select your level",

    "candidates.form.resume.title": "Resume",
    "candidates.form.resume.label": "Upload your CV (PDF, DOC, DOCX - Max 5MB)",
    "candidates.form.resume.button": "Select File",

    "candidates.form.additional.title": "Additional Information",
    "candidates.form.additional.permit": "Work Permit Status",
    "candidates.form.additional.permitPlaceholder": "Select your situation",
    "candidates.form.additional.coverLetter": "Cover Letter / Message",
    "candidates.form.additional.coverLetterPlaceholder": "Tell us about yourself, your experience and why you would like to work in Canada...",

    "candidates.form.security.title": "Security Verification",
    "candidates.form.security.captcha": "Verification: What is {num1} + {num2}? *",
    "candidates.form.security.captchaPlaceholder": "Enter the result",
    "candidates.form.security.disclaimer": "This verification helps us prevent automatic submissions.",
    "candidates.form.security.honeypot": "Website (leave blank)",

    "candidates.form.submit.idle": "Send Application",
    "candidates.form.submit.submitting": "Sending...",
    "candidates.form.submit.success.title": "Application Sent!",
    "candidates.form.submit.success.desc": "We have received your information. We will contact you soon.",
    "candidates.form.submit.success.cardTitle": "Thank you for your application!",
    "candidates.form.submit.success.cardDesc": "We have received your information correctly. Our team will review your profile and contact you soon.",
    "candidates.form.submit.success.again": "Send another application",

    "candidates.form.error.title": "Error",
    "candidates.form.error.fileSize": "File too large",
    "candidates.form.error.fileSizeDesc": "The file must be less than 5MB",
    "candidates.form.error.fileType": "Invalid file type",
    "candidates.form.error.fileTypeDesc": "Only PDF or Word files (.doc, .docx) are allowed",
    "candidates.form.error.captcha": "Incorrect CAPTCHA",
    "candidates.form.error.captchaDesc": "Please correctly solve the math problem.",
    "candidates.form.error.rateLimit": "Submission limit reached",
    "candidates.form.error.rateLimitDesc": "You can only send 3 applications per day. Try again tomorrow.",
    "candidates.form.error.invalidEmail": "Invalid email",
    "candidates.form.error.invalidEmailDesc": "Please enter a valid email.",
    "candidates.form.error.missingFields": "Missing required fields",
    "candidates.form.error.missingFieldsDesc": "Please complete all required fields.",
    "candidates.form.error.config": "Configuration Error: Resume storage is not configured. Please contact the administrator.",
    "candidates.form.error.upload": "Error uploading resume. Please try again.",
    "candidates.form.error.generic": "Error sending application",

    // Dropdown Options
    "candidates.form.education.secondary": "High School",
    "candidates.form.education.technical": "Technical",
    "candidates.form.education.bachelors": "Bachelor's",
    "candidates.form.education.masters": "Master's",
    "candidates.form.education.phd": "PhD",

    "candidates.form.language.basic": "Basic",
    "candidates.form.language.intermediate": "Intermediate",
    "candidates.form.language.advanced": "Advanced",
    "candidates.form.language.native": "Native / Fluent",

    "candidates.form.permit.none": "I don't have a work permit",
    "candidates.form.permit.holiday": "Working Holiday Visa",
    "candidates.form.permit.active": "Active work permit",
    "candidates.form.permit.resident": "Permanent resident",
    "candidates.form.permit.citizen": "Canadian citizen",

    "candidates.form.sector.tech": "Technology / IT",
    "candidates.form.sector.engineering": "Engineering",
    "candidates.form.sector.healthcare": "Health / Healthcare",
    "candidates.form.sector.education": "Education",
    "candidates.form.sector.agriculture": "Agriculture",
    "candidates.form.sector.finance": "Finance",
    "candidates.form.sector.manufacturing": "Manufacturing",
    "candidates.form.sector.construction": "Construction",
    "candidates.form.sector.hospitality": "Hospitality / Tourism",
    "candidates.form.sector.logistics": "Transport / Logistics",
    "candidates.form.sector.other": "Other",

    "candidates.form.country.argentina": "Argentina",
    "candidates.form.country.bolivia": "Bolivia",
    "candidates.form.country.brazil": "Brazil",
    "candidates.form.country.chile": "Chile",
    "candidates.form.country.colombia": "Colombia",
    "candidates.form.country.costa_rica": "Costa Rica",
    "candidates.form.country.cuba": "Cuba",
    "candidates.form.country.ecuador": "Ecuador",
    "candidates.form.country.el_salvador": "El Salvador",
    "candidates.form.country.guatemala": "Guatemala",
    "candidates.form.country.haiti": "Haiti",
    "candidates.form.country.honduras": "Honduras",
    "candidates.form.country.mexico": "Mexico",
    "candidates.form.country.nicaragua": "Nicaragua",
    "candidates.form.country.panama": "Panama",
    "candidates.form.country.paraguay": "Paraguay",
    "candidates.form.country.peru": "Peru",
    "candidates.form.country.dominican_republic": "Dominican Republic",
    "candidates.form.country.uruguay": "Uruguay",
    "candidates.form.country.venezuela": "Venezuela",
    "candidates.form.country.other": "Other",

    // About Page
    "about.hero.title": "About HR-CALATIN",
    "about.hero.subtitle": "We are the bridge connecting Latin American talent with Canadian opportunities",
    "about.mission.title": "Our Mission",
    "about.mission.description": "To connect the best talent from Latin America with Canadian companies, facilitating labor integration and creating real growth opportunities for professionals and visionary employers.",
    "about.vision.title": "Our Vision",
    "about.vision.description": "To become the leading talent exchange platform between Latin America and Canada, recognized for our commitment to quality, integration, and long-term success.",
    "about.values.title": "Our Values",
    "about.values.description": "Integrity, excellence, cultural respect, and commitment to the success of both candidates and employers guide every decision we make.",
    "about.story.title": "Our Story",
    "about.story.p1": "HR-CALATIN was born from the vision of creating meaningful connections between Latin American professionals and Canadian employers. We recognized the incredible talent pool in Latin America and the growing demand for skilled professionals in Canada.",
    "about.story.p2": "Our founders, with extensive experience in both Latin American and Canadian labor markets, understood the challenges that both candidates and employers face in cross-border recruitment. Language barriers, cultural differences, and complex immigration processes often prevented perfect matches from happening.",
    "about.story.p3": "We set out to change that. By combining deep market knowledge, personalized service, and comprehensive support, we've successfully placed hundreds of professionals in rewarding Canadian careers while helping companies build diverse, talented teams.",
    "about.story.p4": "Today, we continue to grow and evolve, always maintaining our commitment to quality, integrity, and the success of everyone we serve.",
    "about.different.title": "Why We're Different",
    "about.different.cultural.title": "Cultural Bridge Experts",
    "about.different.cultural.description": "We don't just match resumes to job descriptions. We understand both Latin American and Canadian work cultures, ensuring seamless integration and long-term success.",
    "about.different.support.title": "End-to-End Support",
    "about.different.support.description": "From initial application to successful integration, we provide comprehensive support. We're with you every step of the way, ensuring a smooth transition for candidates and peace of mind for employers.",
    "about.different.quality.title": "Quality Over Quantity",
    "about.different.quality.description": "We focus on making the right connections, not just making connections. Every candidate is thoroughly vetted, and every employer opportunity is carefully evaluated to ensure mutual success.",
    "about.different.partnership.title": "True Partnership Approach",
    "about.different.partnership.description": "We're not just a service provider - we're your partner in success. Your goals become our goals, and we invest in long-term relationships built on trust and results.",

    // Get Started Page
    "getStarted.hero.title": "Get Started Today",
    "getStarted.hero.subtitle": "Choose your path and begin your journey with HR-CALATIN Interexchange",
    "getStarted.employer.title": "I'm an Employer",
    "getStarted.employer.subtitle": "Looking to hire exceptional Latin American talent",
    "getStarted.employer.item1": "Access pre-vetted candidate profiles",
    "getStarted.employer.item2": "Post job openings to targeted audience",
    "getStarted.employer.item3": "Receive personalized talent recommendations",
    "getStarted.employer.item4": "Get integration and onboarding support",
    "getStarted.employer.button": "Register as Employer",
    "getStarted.candidate.title": "I'm a Candidate",
    "getStarted.candidate.subtitle": "Seeking career opportunities in Canada",
    "getStarted.candidate.item1": "Create professional profile and resume",
    "getStarted.candidate.item2": "Browse exclusive job opportunities",
    "getStarted.candidate.item3": "Access career coaching and resources",
    "getStarted.candidate.item4": "Receive cultural integration support",
    "getStarted.candidate.button": "Register as Candidate",
    "getStarted.help.title1": "Not Sure Which Path to",
    "getStarted.help.title2": "Choose",
    "getStarted.help.subtitle": "Our team is here to help you navigate the best option for your needs. Contact us for personalized guidance.",
    "getStarted.help.button": "Contact Our Team",

    // Employers Page
    "employers.hero.title1": "Find Your Next",
    "employers.hero.title2": "Top Performer",
    "employers.hero.subtitle": "Access pre-qualified Latin American professionals ready to drive your business forward",
    "employers.hero.button": "Post Your First Job Opening",

    "employers.why.title": "International Talent Solutions",
    "employers.why.subtitle": "We eliminate cross-border hiring barriers so you can focus on growing.",
    "employers.why.talent.title": "Rigorous Validation",
    "employers.why.talent.description": "We verify the work history, skills, and language level of each candidate to ensure total compliance with Canadian regulations.",
    "employers.why.matching.title": "Custom Match",
    "employers.why.matching.description": "Candidates who not only fill a vacancy, but align with your industry's vision and technical needs.",
    "employers.why.integration.title": "Rapid Adaptation",
    "employers.why.integration.description": "Cultural integration resources and labor resources so the new talent joins the team without friction and becomes productive immediately.",
    "employers.why.compliance.title": "Legal Security",
    "employers.why.compliance.description": "Expert advice on migration procedures. Full compliance with the law without complications for your company.",
    "employers.why.cost.title": "Smart Savings",
    "employers.why.cost.description": "Optimize your budget. Lower hiring costs and faster response times than traditional recruitment.",
    "employers.why.partnership.title": "Backup and Guarantee",
    "employers.why.partnership.description": "Your investment is protected. We offer continuous support and a replacement guarantee at no cost if the candidate leaves or does not meet expectations within the agreed period (30-90 days).",

    "employers.services.title": "Our Employer Services",
    "employers.services.subtitle": "Comprehensive talent solutions designed for the Canadian business.",
    "employers.services.search.title": "Custom Talent Search",
    "employers.services.search.description": "Tell us what you need. We locate the perfect candidates within our exclusive network in record time.",
    "employers.services.assessment.title": "Competency Evaluation",
    "employers.services.assessment.description": "Technical and soft skills validation to ensure the candidate is 100% ready for the position.",
    "employers.services.training.title": "Technical Training & Standard Alignment",
    "employers.services.training.description": "We train candidates under your company's regulations and technical requirements to ensure talent is productive from day one.",
    "employers.services.onboarding.title": "Strategic Onboarding (90-Day Support)",
    "employers.services.onboarding.description": "We accompany the new collaborator during their first quarter, eliminating operational barriers and guaranteeing long-term hiring success.",

    "employers.collaborations.title": "Technology Solutions",
    "employers.collaborations.titleHighlight": "& Alliances",
    "employers.collaborations.subtitle": "Beyond talent. Thanks to our strategic business alliance, we enhance your digital infrastructure with specialized IT services.",
    "employers.collaborations.powerbi.title": "Data Analysis (Power BI)",
    "employers.collaborations.powerbi.description": "Transform data into decisions. We design custom dashboards to visualize your business performance in real time.",
    "employers.collaborations.web.title": "Custom Web Development",
    "employers.collaborations.web.description": "Your digital image matters. We create everything from corporate websites to modern, responsive e-commerce platforms focused on selling.",
    "employers.collaborations.microsoft.title": "Microsoft 365 Administration",
    "employers.collaborations.microsoft.description": "Comprehensive cloud management. We handle configuration, licenses, and security of your M365 environment so your team works without interruptions.",
    "employers.collaborations.webapp.title": "Web Application Management",
    "employers.collaborations.webapp.description": "Continuous technical support. Installation, maintenance, and optimization of your digital tools to ensure maximum operational performance.",

    "employers.cta.title": "Ready to Build Your Dream Team?",
    "employers.cta.subtitle": "Register your company today and start accessing exceptional Latin American talent",
    "employers.cta.register": "Register Your Company",
    "employers.cta.consultation": "Schedule a Consultation",

    // Contact Page
    "contact.hero.title": "Get in Touch",
    "contact.hero.subtitle": "Ready to start your journey? We're here to help",
    "contact.location.title": "Location",
    "contact.email.title": "Email",
    "contact.phone.title": "Phone",
    "contact.hours.title": "Business Hours",
    "contact.hours.weekdays": "Mon-Fri: 9AM - 6PM EST",
    "contact.hours.weekend": "Sat-Sun: Closed",
    "contact.connect.title": "Let's Connect",
    "contact.connect.subtitle": "Whether you're an employer looking for talent or a candidate seeking opportunities, we're ready to help",
    "contact.connect.employers.title": "For Employers",
    "contact.connect.employers.description": "Interested in accessing our talent pool or learning more about our services?",
    "contact.connect.candidates.title": "For Candidates",
    "contact.connect.candidates.description": "Ready to start your Canadian career journey? Need help with your application?",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.employers": "Para Empleadores",
    "nav.candidates": "Para Candidatos",
    "nav.contact": "Contáctanos",
    "nav.getStarted": "Comenzar",
    "nav.about": "Sobre Nosotros",

    // Home Page
    "home.hero.title1": "Conectando Talento,",
    "home.hero.title2": "Construyendo Futuros",
    "home.hero.subtitle": "Conectamos profesionales latinoamericanos con oportunidades canadienses a través de HR-CALATIN Interexchange",
    "home.hero.employers": "Para Empleadores",
    "home.hero.candidates": "Para Candidatos",

    "home.mission.title": "Nuestra",
    "home.mission.titleHighlight": "Misión",
    "home.mission.description": "Conectamos el mejor talento de Latinoamérica con empresas canadienses. Facilitamos la integración laboral creando oportunidades de crecimiento real para profesionales y empleadores visionarios.",

    "home.why.title": "¿Por qué",
    "home.why.titleHighlight": "HR-CALATIN",
    "home.why.subtitle": "Conexiones y resultados excelentes",
    "home.why.expertise.title": "Expertos en Ambos Mundos",
    "home.why.expertise.description": "Dominamos el mercado canadiense y conocemos el potencial latino. Alineamos las metas de la empresa con las aspiraciones del candidato para un encaje perfecto.",
    "home.why.quality.title": "Calidad Garantizada",
    "home.why.quality.description": "Validación rigurosa. Las empresas reciben perfiles de alto nivel y los candidatos acceden a ofertas serias y confiables. Sin pérdidas de tiempo.",
    "home.why.support.title": "Integración Exitosa",
    "home.why.support.description": "Acompañamiento total. Facilitamos la llegada y adaptación del profesional, asegurando tranquilidad para el empleador y confianza para el nuevo talento.",

    "home.portal.employers.title": "Para Empleadores",
    "home.portal.employers.description": "Accede a un grupo selecto de profesionales latinoamericanos calificados listos para contribuir al éxito de tu negocio canadiense.",
    "home.portal.employers.item1": "Búsqueda y emparejamiento personalizado de talento",
    "home.portal.employers.item2": "Evaluaciones integrales de habilidades",
    "home.portal.employers.item3": "Soporte de integración e incorporación",
    "home.portal.employers.button": "Explorar Portal de Empleadores",

    "home.portal.candidates.title": "Para Candidatos",
    "home.portal.candidates.description": "Lanza tu carrera canadiense con orientación experta, recursos y acceso a los mejores empleadores que buscan tu talento.",
    "home.portal.candidates.item1": "Herramientas profesionales para crear currículum",
    "home.portal.candidates.item2": "Búsqueda de empleo y seguimiento de aplicaciones",
    "home.portal.candidates.item3": "Recursos de integración cultural",
    "home.portal.candidates.button": "Explorar Portal de Candidatos",

    "home.pathways.title": "Vías Legales",
    "home.pathways.titleHighlight": " hacia Canadá",
    "home.pathways.subtitle": "En HR-CALATIN somos el puente entre la excelencia profesional de Latinoamérica y la visión de las empresas canadienses. Creamos el match perfecto: talento listo para aportar valor inmediato y oportunidades de carrera que transforman vidas.",
    "home.pathways.holiday.title": "Talento Joven (Working Holiday)",
    "home.pathways.holiday.description": "Fuerza Laboral Joven y Flexible. Programas ágiles para talento de Chile y Costa Rica. Una solución perfecta para cubrir necesidades temporales o periodos de prueba que pueden evolucionar a posiciones permanentes.",
    "home.pathways.fta.title": "Tratados de Libre Comercio: Talento sin Fronteras",
    "home.pathways.fta.description": "Aprovechamos los acuerdos con Colombia, Panamá, Perú, Chile y México para garantizar la entrada rápida de expertos de posiciones de alta demanda a Canadá.",
    "home.pathways.fta.engineering": "Enfoque: Velocidad y Profesionales Calificados (Colombia, Panamá, etc.)",
    "home.pathways.fta.engineeringDesc": "",
    "home.pathways.fta.healthcare": "",
    "home.pathways.fta.healthcareDesc": "",
    "home.pathways.fta.education": "",
    "home.pathways.fta.educationDesc": "",
    "home.pathways.sawp.title": "Sector Agrícola (SAWP)",
    "home.pathways.sawp.description": "Personal para el Agro (SAWP). Cubrimos sus temporadas de cosecha con trabajadores experimentados de México y el Caribe. Garantizamos mano de obra confiable y legal para el campo canadiense.",

    "home.stats.placements": "Colocaciones Exitosas",
    "home.stats.companies": "Empresas Asociadas",
    "home.stats.satisfaction": "Tasa de Satisfacción",
    "home.stats.experience": "Años de Experiencia",

    // Candidates Page
    "candidates.hero.title1": "Tu Carrera",
    "candidates.hero.title2": "Canadiense Comienza Aquí",
    "candidates.hero.subtitle": "Transforma tus sueños profesionales en realidad con orientación experta y acceso a los mejores empleadores canadienses",
    "candidates.hero.button": "Crea Tu Perfil Hoy",

    "candidates.why.title": "Tu Aliado para Triunfar en Canadá",
    "candidates.why.subtitle": "No somos solo una bolsa de trabajo. Somos tu puente seguro hacia una carrera internacional exitosa.",
    "candidates.why.jobs.title": "Oportunidades Verificadas",
    "candidates.why.jobs.description": "Accede a vacantes reales en empresas canadienses que buscan talento latino específicamente. Sin ofertas falsas, solo crecimiento.",
    "candidates.why.resume.title": "CV de Alto Impacto",
    "candidates.why.resume.description": "Transforma tu hoja de vida al 'Estándar Canadiense'. Herramientas y expertos para que tu perfil pase todos los filtros de selección.",
    "candidates.why.culture.title": "Dominio Cultural",
    "candidates.why.culture.description": "Aprende las claves del entorno laboral canadiense. Te enseñamos lo que no está en los libros para que te integres desde el día uno.",
    "candidates.why.relocation.title": "Soporte de Llegada",
    "candidates.why.relocation.description": "Tu mudanza, simplificada. Orientación clara sobre trámites migratorios y vivienda para que llegues con tranquilidad.",
    "candidates.why.skills.title": "Nivelación de Habilidades",
    "candidates.why.skills.description": "Cierra la brecha técnica. Cursos y certificaciones para alinear tus competencias con lo que la industria canadiense exige hoy.",
    "candidates.why.coaching.title": "Estrategia de Carrera",
    "candidates.why.coaching.description": "No postules a ciegas. Recibe mentoría experta y simulacros de entrevista para convertir oportunidades en ofertas de trabajo.",
    "candidates.why.legal.title": "Mentoria en Metas y Carrera",
    "candidates.why.legal.description": "No solo te acompañamos en el proceso, impulsamos tu futuro. Guiamos tu trayectoria profesional para que alcances tus metas, con éxito garantizado dentro o fuera de Canadá.",

    "candidates.training.title": "Capacitación y",
    "candidates.training.titleHighlight": "Apoyo de Integración",
    "candidates.training.subtitle": "Preparamos a los profesionales para el éxito en Canadá con programas integrales de capacitación e integración",
    "candidates.training.language.title": "Capacitación de Idiomas",
    "candidates.training.language.description": "Cursos intensivos de inglés y francés diseñados para lograr una comunicación efectiva en el entorno profesional canadiense.",
    "candidates.training.resume.title": "Creación de Currículum",
    "candidates.training.resume.description": "Asesoría experta para adaptar tu perfil profesional y CV a los estándares y formatos que exigen los reclutadores en Canadá.",
    "candidates.training.arrival.title": "Primeros Pasos en Canadá",
    "candidates.training.arrival.description": "Te acompañamos en tus trámites iniciales: gestión de línea telefónica, apertura de cuenta bancaria y otros requisitos esenciales para tu nueva vida.",
    "candidates.training.button": "Saber más",

    "candidates.path.title": "Tu Camino al Éxito",
    "candidates.path.subtitle": "Cuatro simples pasos para lanzar tu carrera canadiense",
    "candidates.path.step1.title": "Regístrate",
    "candidates.path.step1.description": "Crea tu cuenta gratuita y completa tu perfil profesional",
    "candidates.path.step2.title": "Crea tu CV",
    "candidates.path.step2.description": "Usa nuestras herramientas para crear un CV atractivo al estándar canadiense",
    "candidates.path.step3.title": "Aplica",
    "candidates.path.step3.description": "Explora oportunidades y aplica a posiciones que coincidan con tus habilidades",
    "candidates.path.step4.title": "Inicia tu Carrera",
    "candidates.path.step4.description": "Consigue empleo y recibe apoyo continuo durante tu transición",

    "candidates.tools.title": "Herramientas Poderosas para Tu Éxito",
    "candidates.tools.subtitle": "Todo lo que necesitas para destacar y triunfar",
    "candidates.tools.resume.title": "Constructor Inteligente de CV",
    "candidates.tools.resume.description": "Sugerencias impulsadas por IA, plantillas específicas por industria y retroalimentación en tiempo real para crear el CV perfecto",
    "candidates.tools.search.title": "Panel de Búsqueda de Empleo",
    "candidates.tools.search.description": "Filtrado avanzado, recomendaciones personalizadas y seguimiento de aplicaciones en un solo lugar",
    "candidates.tools.learning.title": "Recursos de Aprendizaje",
    "candidates.tools.learning.description": "Guías completas sobre cultura laboral canadiense, consejos de entrevista y desarrollo profesional",
    "candidates.tools.acceleration.title": "Programa de Aceleración de Carrera",
    "candidates.tools.acceleration.description": "Acceso exclusivo a mentoría, eventos de networking y talleres de desarrollo profesional",

    "candidates.apply.title": "¡Aplica Ahora!",
    "candidates.apply.subtitle": "Da el primer paso hacia tu carrera canadiense. Completa nuestro formulario de aplicación y nuestro equipo te contactará.",

    "candidates.cta.title": "Contáctanos",
    "candidates.cta.subtitle": "¿Tienes preguntas sobre nuestros programas o servicios? Estamos aquí para ayudarte en cada paso del camino.",
    "candidates.cta.button": "Contáctanos",

    // Application Form
    "candidates.form.personal.title": "Información Personal",
    "candidates.form.personal.name": "Nombre Completo *",
    "candidates.form.personal.namePlaceholder": "Juan Pérez",
    "candidates.form.personal.email": "Correo Electrónico *",
    "candidates.form.personal.emailPlaceholder": "juan@ejemplo.com",
    "candidates.form.personal.phone": "Teléfono",
    "candidates.form.personal.phonePlaceholder": "+52 55 1234 5678",
    "candidates.form.personal.country": "País de Residencia *",
    "candidates.form.personal.countryPlaceholder": "Selecciona tu país",
    "candidates.form.personal.city": "Ciudad",
    "candidates.form.personal.cityPlaceholder": "Ciudad de México",

    "candidates.form.professional.title": "Información Profesional",
    "candidates.form.professional.profession": "Profesión / Área de Trabajo *",
    "candidates.form.professional.professionPlaceholder": "Ingeniero de Software",
    "candidates.form.professional.experience": "Años de Experiencia",
    "candidates.form.professional.experiencePlaceholder": "5",
    "candidates.form.professional.education": "Nivel de Educación",
    "candidates.form.professional.educationPlaceholder": "Selecciona tu nivel",
    "candidates.form.professional.sector": "Sector de Interés",
    "candidates.form.professional.sectorPlaceholder": "Selecciona un sector",
    "candidates.form.professional.linkedin": "LinkedIn URL",
    "candidates.form.professional.linkedinPlaceholder": "https://linkedin.com/in/tu-perfil",

    "candidates.form.languages.title": "Idiomas",
    "candidates.form.languages.english": "Nivel de Inglés",
    "candidates.form.languages.french": "Nivel de Francés",
    "candidates.form.languages.placeholder": "Selecciona tu nivel",

    "candidates.form.resume.title": "Currículum",
    "candidates.form.resume.label": "Sube tu CV (PDF, DOC, DOCX - Max 5MB)",
    "candidates.form.resume.button": "Seleccionar archivo",

    "candidates.form.additional.title": "Información Adicional",
    "candidates.form.additional.permit": "Estado de Permiso de Trabajo",
    "candidates.form.additional.permitPlaceholder": "Selecciona tu situación",
    "candidates.form.additional.coverLetter": "Carta de Presentación / Mensaje",
    "candidates.form.additional.coverLetterPlaceholder": "Cuéntanos sobre ti, tu experiencia y por qué te gustaría trabajar en Canadá...",

    "candidates.form.security.title": "Verificación de Seguridad",
    "candidates.form.security.captcha": "Verificación: ¿Cuánto es {num1} + {num2}? *",
    "candidates.form.security.captchaPlaceholder": "Ingresa el resultado",
    "candidates.form.security.disclaimer": "Esta verificación nos ayuda a prevenir envíos automáticos.",
    "candidates.form.security.honeypot": "Website (déjalo en blanco)",

    "candidates.form.submit.idle": "Enviar Aplicación",
    "candidates.form.submit.submitting": "Enviando...",
    "candidates.form.submit.success.title": "¡Aplicación enviada!",
    "candidates.form.submit.success.desc": "Hemos recibido tu información. Te contactaremos pronto.",
    "candidates.form.submit.success.cardTitle": "¡Gracias por tu aplicación!",
    "candidates.form.submit.success.cardDesc": "Hemos recibido tu información correctamente. Nuestro equipo revisará tu perfil y te contactará pronto.",
    "candidates.form.submit.success.again": "Enviar otra aplicación",

    "candidates.form.error.title": "Error",
    "candidates.form.error.fileSize": "Archivo muy grande",
    "candidates.form.error.fileSizeDesc": "El archivo debe ser menor a 5MB",
    "candidates.form.error.fileType": "Tipo de archivo no válido",
    "candidates.form.error.fileTypeDesc": "Solo se permiten archivos PDF o Word (.doc, .docx)",
    "candidates.form.error.captcha": "CAPTCHA incorrecto",
    "candidates.form.error.captchaDesc": "Por favor resuelve correctamente el problema matemático.",
    "candidates.form.error.rateLimit": "Límite de envíos alcanzado",
    "candidates.form.error.rateLimitDesc": "Solo puedes enviar 3 aplicaciones por día. Inténtalo mañana.",
    "candidates.form.error.invalidEmail": "Email inválido",
    "candidates.form.error.invalidEmailDesc": "Por favor ingresa un email válido.",
    "candidates.form.error.missingFields": "Campos requeridos faltantes",
    "candidates.form.error.missingFieldsDesc": "Por favor completa todos los campos requeridos.",
    "candidates.form.error.config": "Error de configuración: El almacenamiento de currículums no está configurado. Por favor contacta al administrador.",
    "candidates.form.error.upload": "Error al subir el currículum. Por favor intenta de nuevo.",
    "candidates.form.error.generic": "Error al enviar la aplicación",

    // Dropdown Options
    "candidates.form.education.secondary": "Secundaria / High School",
    "candidates.form.education.technical": "Técnico / Technical",
    "candidates.form.education.bachelors": "Licenciatura / Bachelor's",
    "candidates.form.education.masters": "Maestría / Master's",
    "candidates.form.education.phd": "Doctorado / PhD",

    "candidates.form.language.basic": "Básico",
    "candidates.form.language.intermediate": "Intermedio",
    "candidates.form.language.advanced": "Avanzado",
    "candidates.form.language.native": "Nativo / Fluido",

    "candidates.form.permit.none": "No tengo permiso de trabajo",
    "candidates.form.permit.holiday": "Working Holiday Visa",
    "candidates.form.permit.active": "Permiso de trabajo activo",
    "candidates.form.permit.resident": "Residente permanente",
    "candidates.form.permit.citizen": "Ciudadano canadiense",

    "candidates.form.sector.tech": "Tecnología / IT",
    "candidates.form.sector.engineering": "Ingeniería",
    "candidates.form.sector.healthcare": "Salud / Healthcare",
    "candidates.form.sector.education": "Educación",
    "candidates.form.sector.agriculture": "Agricultura",
    "candidates.form.sector.finance": "Finanzas",
    "candidates.form.sector.manufacturing": "Manufactura",
    "candidates.form.sector.construction": "Construcción",
    "candidates.form.sector.hospitality": "Hotelería / Turismo",
    "candidates.form.sector.logistics": "Transporte / Logística",
    "candidates.form.sector.other": "Otro",

    "candidates.form.country.argentina": "Argentina",
    "candidates.form.country.bolivia": "Bolivia",
    "candidates.form.country.brazil": "Brasil",
    "candidates.form.country.chile": "Chile",
    "candidates.form.country.colombia": "Colombia",
    "candidates.form.country.costa_rica": "Costa Rica",
    "candidates.form.country.cuba": "Cuba",
    "candidates.form.country.ecuador": "Ecuador",
    "candidates.form.country.el_salvador": "El Salvador",
    "candidates.form.country.guatemala": "Guatemala",
    "candidates.form.country.haiti": "Haití",
    "candidates.form.country.honduras": "Honduras",
    "candidates.form.country.mexico": "México",
    "candidates.form.country.nicaragua": "Nicaragua",
    "candidates.form.country.panama": "Panamá",
    "candidates.form.country.paraguay": "Paraguay",
    "candidates.form.country.peru": "Perú",
    "candidates.form.country.dominican_republic": "República Dominicana",
    "candidates.form.country.uruguay": "Uruguay",
    "candidates.form.country.venezuela": "Venezuela",
    "candidates.form.country.other": "Otro",

    // About Page
    "about.hero.title": "Acerca de HR-CALATIN",
    "about.hero.subtitle": "Somos el puente que conecta el talento latinoamericano con las oportunidades canadienses",
    "about.mission.title": "Nuestra Misión",
    "about.mission.description": "Conectar el mejor talento de Latinoamérica con empresas canadienses, facilitando la integración laboral y creando oportunidades de crecimiento real para profesionales y empleadores visionarios.",
    "about.vision.title": "Nuestra Visión",
    "about.vision.description": "Convertirnos en la plataforma líder de intercambio de talento entre Latinoamérica y Canadá, reconocidos por nuestro compromiso con la calidad, la integración y el éxito a largo plazo.",
    "about.values.title": "Nuestros Valores",
    "about.values.description": "Integridad, excelencia, respeto cultural y compromiso con el éxito de candidatos y empleadores guían cada decisión que tomamos.",
    "about.story.title": "Nuestra Historia",
    "about.story.p1": "HR-CALATIN nació de la visión de crear conexiones significativas entre profesionales latinoamericanos y empleadores canadienses. Reconocimos el increíble talento en Latinoamérica y la creciente demanda de profesionales calificados en Canadá.",
    "about.story.p2": "Nuestros fundadores, con amplia experiencia en los mercados laborales latinoamericano y canadiense, comprendieron los desafíos que enfrentan candidatos y empleadores en el reclutamiento transfronterizo. Las barreras idiomáticas, diferencias culturales y procesos migratorios complejos a menudo impedían que se dieran emparejamientos perfectos.",
    "about.story.p3": "Nos propusimos cambiar eso. Combinando conocimiento profundo del mercado, servicio personalizado y apoyo integral, hemos colocado exitosamente a cientos de profesionales en carreras canadienses gratificantes mientras ayudamos a las empresas a construir equipos diversos y talentosos.",
    "about.story.p4": "Hoy continuamos creciendo y evolucionando, manteniendo siempre nuestro compromiso con la calidad, la integridad y el éxito de todos a quienes servimos.",
    "about.different.title": "Por Qué Somos Diferentes",
    "about.different.cultural.title": "Expertos en Puentes Culturales",
    "about.different.cultural.description": "No solo emparejamos currículums con descripciones de trabajo. Entendemos las culturas laborales latinoamericana y canadiense, asegurando integración perfecta y éxito a largo plazo.",
    "about.different.support.title": "Apoyo Integral",
    "about.different.support.description": "Desde la aplicación inicial hasta la integración exitosa, brindamos apoyo integral. Estamos contigo en cada paso del camino, asegurando una transición fluida para los candidatos y tranquilidad para los empleadores.",
    "about.different.quality.title": "Calidad Sobre Cantidad",
    "about.different.quality.description": "Nos enfocamos en hacer las conexiones correctas, no solo en hacer conexiones. Cada candidato es rigurosamente evaluado y cada oportunidad de empleo es cuidadosamente evaluada para asegurar el éxito mutuo.",
    "about.different.partnership.title": "Enfoque de Verdadera Asociación",
    "about.different.partnership.description": "No somos solo un proveedor de servicios - somos tu socio en el éxito. Tus objetivos se convierten en nuestros objetivos, e invertimos en relaciones a largo plazo construidas sobre confianza y resultados.",

    // Get Started Page
    "getStarted.hero.title": "Comienza Hoy",
    "getStarted.hero.subtitle": "Elige tu camino y comienza tu viaje con HR-CALATIN Interexchange",
    "getStarted.employer.title": "Soy un Empleador",
    "getStarted.employer.subtitle": "Buscando contratar talento latinoamericano excepcional",
    "getStarted.employer.item1": "Accede a perfiles de candidatos pre-verificados",
    "getStarted.employer.item2": "Publica vacantes a audiencia específica",
    "getStarted.employer.item3": "Recibe recomendaciones personalizadas de talento",
    "getStarted.employer.item4": "Obtén soporte de integración e incorporación",
    "getStarted.employer.button": "Registrarse como Empleador",
    "getStarted.candidate.title": "Soy un Candidato",
    "getStarted.candidate.subtitle": "Buscando oportunidades profesionales en Canadá",
    "getStarted.candidate.item1": "Crea perfil profesional y currículum",
    "getStarted.candidate.item2": "Explora oportunidades laborales exclusivas",
    "getStarted.candidate.item3": "Accede a asesoría profesional y recursos",
    "getStarted.candidate.item4": "Recibe apoyo de integración cultural",
    "getStarted.candidate.button": "Registrarse como Candidato",
    "getStarted.help.title1": "¿No Estás Seguro Qué Camino",
    "getStarted.help.title2": "Elegir",
    "getStarted.help.subtitle": "Nuestro equipo está aquí para ayudarte a navegar la mejor opción para tus necesidades. Contáctanos para orientación personalizada.",
    "getStarted.help.button": "Contacta a Nuestro Equipo",

    // Employers Page
    "employers.hero.title1": "Encuentra a Tu",
    "employers.hero.title2": "Próximo Talento",
    "employers.hero.subtitle": "Accede a profesionales latinoamericanos precalificados listos para impulsar tu negocio",
    "employers.hero.button": "Publica Tu Primera Vacante",

    "employers.why.title": "Soluciones de Talento Internacional",
    "employers.why.subtitle": "Eliminamos las barreras de la contratación transfronteriza para que usted se enfoque en crecer.",
    "employers.why.talent.title": "Validación Rigurosa",
    "employers.why.talent.description": "Verificamos el historial laboral, habilidades y nivel de idioma de cada candidato para asegurar el cumplimiento total de las normativas de Canadá.",
    "employers.why.matching.title": "Match a Medida",
    "employers.why.matching.description": "Candidatos que no solo llenan una vacante, sino que se alinean con la visión y necesidades técnicas de su industria.",
    "employers.why.integration.title": "Adaptación Rápida",
    "employers.why.integration.description": "Recursos de integración cultural y laboral para que el nuevo talento se sume al equipo sin fricciones y sea productivo de inmediato.",
    "employers.why.compliance.title": "Seguridad Legal",
    "employers.why.compliance.description": "Asesoría experta en trámites migratorios. Cumplimiento total de la ley sin complicaciones para su empresa.",
    "employers.why.cost.title": "Ahorro Inteligente",
    "employers.why.cost.description": "Optimice su presupuesto. Menor costo por contratación y tiempos de respuesta más rápidos que el reclutamiento tradicional.",
    "employers.why.partnership.title": "Respaldo y Garantía",
    "employers.why.partnership.description": "Su inversión está protegida. Ofrecemos soporte continuo y una garantía de reemplazo sin costo si el candidato se retira o no cumple expectativas dentro del periodo acordado (30-90 días).",

    "employers.services.title": "Nuestros Servicios para Empleadores",
    "employers.services.subtitle": "Soluciones integrales de talento diseñadas para la empresa canadiense.",
    "employers.services.search.title": "Búsqueda de Talento a Medida",
    "employers.services.search.description": "Díganos qué necesita. Localizamos a los candidatos perfectos dentro de nuestra red exclusiva en tiempo récord.",
    "employers.services.assessment.title": "Evaluación de Competencias",
    "employers.services.assessment.description": "Validación técnica y de habilidades blandas para asegurar que el candidato esté 100% listo para el puesto.",
    "employers.services.training.title": "Technical Training & Standard Alignment",
    "employers.services.training.description": "Entrenamos a los candidatos bajo las normativas y requerimientos técnicos de su empresa para asegurar que el talento sea productivo desde el primer día.",
    "employers.services.onboarding.title": "Onboarding Estratégico (Soporte de 90 días)",
    "employers.services.onboarding.description": "Acompañamos al nuevo colaborador durante su primer trimestre, eliminando barreras operativas y garantizando el éxito de la contratación a largo plazo.",

    "employers.collaborations.title": "Soluciones Tecnológicas",
    "employers.collaborations.titleHighlight": "& Alianzas",
    "employers.collaborations.subtitle": "Más allá del talento. Gracias a nuestra alianza comercial estratégica, potenciamos su infraestructura digital con servicios TI especializados.",
    "employers.collaborations.powerbi.title": "Análisis de Datos (Power BI)",
    "employers.collaborations.powerbi.description": "Transforme datos en decisiones. Diseñamos tableros de control personalizados para visualizar el rendimiento de su negocio en tiempo real.",
    "employers.collaborations.web.title": "Desarrollo Web a Medida",
    "employers.collaborations.web.description": "Su imagen digital importa. Creamos desde sitios corporativos hasta plataformas de e-commerce modernas, responsivas y enfocadas en vender.",
    "employers.collaborations.microsoft.title": "Administración Microsoft 365",
    "employers.collaborations.microsoft.description": "Gestión integral de su nube. Nos encargamos de la configuración, licencias y seguridad de su entorno M365 para que su equipo trabaje sin interrupciones.",
    "employers.collaborations.webapp.title": "Gestión de Aplicaciones Web",
    "employers.collaborations.webapp.description": "Soporte técnico continuo. Instalación, mantenimiento y optimización de sus herramientas digitales para asegurar su máximo rendimiento operativo.",

    "employers.cta.title": "¿Listo para Construir Tu Equipo Ideal?",
    "employers.cta.subtitle": "Registra tu empresa hoy y comienza a acceder a talento latinoamericano excepcional",
    "employers.cta.register": "Registra Tu Empresa",
    "employers.cta.consultation": "Agenda una Consulta",

    // Contact Page
    "contact.hero.title": "Contáctanos",
    "contact.hero.subtitle": "¿Listo para comenzar tu viaje? Estamos aquí para ayudar",
    "contact.location.title": "Ubicación",
    "contact.email.title": "Correo",
    "contact.phone.title": "Teléfono",
    "contact.hours.title": "Horario de Atención",
    "contact.hours.weekdays": "Lun-Vie: 9AM - 6PM EST",
    "contact.hours.weekend": "Sáb-Dom: Cerrado",
    "contact.connect.title": "Conectemos",
    "contact.connect.subtitle": "Ya sea que seas un empleador buscando talento o un candidato buscando oportunidades, estamos listos para ayudar",
    "contact.connect.employers.title": "Para Empleadores",
    "contact.connect.employers.description": "¿Interesado en acceder a nuestro pool de talento o conocer más sobre nuestros servicios?",
    "contact.connect.candidates.title": "Para Candidatos",
    "contact.connect.candidates.description": "¿Listo para comenzar tu carrera canadiense? ¿Necesitas ayuda con tu aplicación?",
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};